# Practical Exam: House sales

RealAgents is a real estate company that focuses on selling houses.

RealAgents sells a variety of types of house in one metropolitan area.

Some houses sell slowly and sometimes require lowering the price in order to find a buyer.

In order to stay competitive, RealAgents would like to optimize the listing prices of the houses it is trying to sell.

They want to do this by predicting the sale price of a house given its characteristics.

If they can predict the sale price in advance, they can decrease the time to sale.


## Data

The dataset contains records of previous houses sold in the area.

| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton'. </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced" (two shared walls), "Semi-detached" (one shared wall), or "Detached" (no shared walls). </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

# Task 1

The team at RealAgents knows that the city that a property is located in makes a difference to the sale price.

Unfortuntately they believe that this isn't always recorded in the data.

Calculate the number of missing values of the `city`.

 - You should use the data in the file "house_sales.csv".

 - Your output should be an object `missing_city`, that contains the number of missing values in this column.

In [1]:
import pandas as pd
import numpy as np

house = pd.read_csv("house_sales.csv")

missing_city_df = house[house['city'] == '--']
missing_city = missing_city_df.city.count()
missing_city

73

# Task 2

Before you fit any models, you will need to make sure the data is clean.

The table below shows what the data should look like.

Create a cleaned version of the dataframe.

 - You should start with the data in the file "house_sales.csv".

 - Your output should be a dataframe named `clean_data`.

 - All column names and values should match the table below.


| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton' </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced", "Semi-detached", or "Detached". </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

In [5]:
import pandas as pd

df = pd.read_csv("house_sales.csv" , na_values=["--"])

df['city'].fillna('Unknown', inplace=True)

df.dropna(subset=['sale_price'], inplace=True)

df['sale_date'].fillna('2023-01-01', inplace=True)

df['months_listed'].fillna(df['months_listed'].mean().round(1), inplace=True)

df['bedrooms'].fillna(round(df['bedrooms'].mean()), inplace=True)

df['house_type'].replace({'Det.' : 'Detached' ,'Terr.' : 'Terraced' , 'Semi' :  'Semi-detached'} , inplace=True)

df['area'] = df['area'].str.replace(' sq.m.', '').astype(float)

df['area'].fillna(df['area'].mean(), inplace=True)

clean_data = df.copy()
clean_data

<ipython-input-5-9abb501042cd>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna('Unknown', inplace=True)
<ipython-input-5-9abb501042cd>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sale_date'].fillna('2023-01-01', inplace=True)
<ipython-input-5-9abb501042cd>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['months_listed'].fillna(df['months_listed'].mean().round(), inplace=True)
<ipython-input-5-9abb501042cd>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bedrooms'].fillna(round(df['bedrooms'].mean()), inplace=True)
<ipython-input-5-9abb501042cd>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['house_type'].replace({'Det.' : 'Detached' ,'Terr.' : 'Terraced' , 'Semi' :  'Semi-detached'} , inplace=True)
<ipython-input-5-9abb501042cd>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['area'].fillna(df['area'].mean(), inplace=True)

,house_id,city,sale_price,sale_date,months_listed,bedrooms,house_type,area
0,1217792,Silvertown,55943,2021-09-12,5.4,2,Semi-detached,107.8
1,1900913,Silvertown,384677,2021-01-17,6.3,5,Detached,498.8
2,1174927,Riverford,281707,2021-11-10,6.9,6,Detached,542.5
3,1773666,Silvertown,373251,2020-04-13,6.1,6,Detached,528.4
4,1258487,Silvertown,328885,2020-09-24,8.7,5,Detached,477.1
...,...,...,...,...,...,...,...,...
1495,1123892,Riverford,198661,2022-02-17,7.3,5,Detached,432.2
1496,1327295,Poppleton,358304,2020-10-10,6.2,6,Detached,599.8
1497,1058161,Riverford,176612,2022-11-01,6.8,4,Detached,359.1
1498,1822037,Teasdale,197827,2021-04-03,5.4,3,Detached,253.7
1499,1679272,Poppleton,162099,2021-12-06,5.0,3,Detached,268.7

# Task 3

The team at RealAgents have told you that they have always believed that the number of bedrooms is the biggest driver of house price.

Producing a table showing the difference in the average sale price by number of bedrooms along with the variance to investigate this question for the team.

 - You should start with the data in the file 'house_sales.csv'.

 - Your output should be a data frame named `price_by_rooms`.

 - It should include the three columns `bedrooms`, `avg_price`, `var_price`.

 - Your answers should be rounded to 1 decimal place.

In [7]:
price_by_rooms = clean_data.groupby('bedrooms')['sale_price'].agg(['mean', 'var'])
price_by_rooms.columns = ['avg_price', 'var_price']
price_by_rooms = price_by_rooms.round(1)
price_by_rooms.reset_index(inplace=True)
price_by_rooms

   bedrooms  avg_price     var_price
0         2    67076.4  5.652896e+08
1         3   154665.1  2.378289e+09
2         4   234704.6  1.725211e+09
3         5   301515.9  2.484328e+09
4         6   375741.3  3.924432e+09

# Task 4

Fit a baseline model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `base_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

train = pd.read_csv("train.csv")
validate = pd.read_csv("validation.csv")

train = train.drop(['sale_date'],axis=1)

label_encoder_house = LabelEncoder()
label_encoder_city = LabelEncoder()
train['house_type'] = label_encoder_house.fit_transform(train['house_type'])
train['city'] = label_encoder_city.fit_transform(train['city'])

X = train.drop(['sale_price'], axis=1)
y = train.sale_price

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

preprocessor = ColumnTransformer(
    transformers=[
        ('num' , 'passthrough',
         X.columns)
    ])

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=40))
])

model.fit(X_train, y_train)
prediction = model.predict(X_test)

mse = mean_squared_error(y_test, prediction)
rmse = np.sqrt(mse).round(1)
print("RMSE:", rmse)

validate2 = validate.copy()
validate2 = validate2.drop(['sale_date'],axis=1)

validate2['house_type'] = label_encoder_house.transform(validate2['house_type'])
validate2['city'] = label_encoder_city.transform(validate2['city'])

base_result = validate2.copy()
base_result['price'] = model.predict(base_result)
base_result

RMSE: 16254.0

     house_id  city  months_listed  bedrooms  house_type   area      price
0     1331375     3            7.7         3           2  209.7   78815.07
1     1630115     3            6.5         4           0  390.6  300732.85
2     1645745     2            7.4         6           0  556.8  407845.03
3     1336775     2            8.8         3           1  208.3  112212.64
4     1888274     2            5.7         4           0  389.2  266473.50
..        ...   ...            ...       ...         ...    ...        ...
295   1986255     2            3.5         6           0  508.9  353526.20
296   1896276     2            8.4         6           0  533.2  394796.28
297   1758223     2            9.5         4           0  367.1  260871.85
298   1752010     0            2.6         3           0  291.3  176186.54
299   1651404     3            7.8         6           0  517.0  427704.55

[300 rows x 7 columns]

# Task 5

Fit a comparison model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `compare_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [16]:
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

X = X
y = y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

comparison_model = LinearRegression()
comparison_model.fit(X_train, y_train)
comparison_predictions = comparison_model.predict(X_test)

comparison_mse = mean_squared_error(y_test, comparison_predictions)
comparison_rmse = np.sqrt(comparison_mse).round(1)
print("RMSE:", comparison_rmse)

compare_result = validate2.copy()
compare_result['price'] = comparison_model.predict(compare_result)
compare_result

RMSE: 26084.6

     house_id  city  months_listed  bedrooms  house_type   area          price
0     1331375     3            7.7         3           2  209.7  116835.208955
1     1630115     3            6.5         4           0  390.6  298552.572930
2     1645745     2            7.4         6           0  556.8  385344.913304
3     1336775     2            8.8         3           1  208.3  124749.522848
4     1888274     2            5.7         4           0  389.2  271354.727321
..        ...   ...            ...       ...         ...    ...            ...
295   1986255     2            3.5         6           0  508.9  349826.394269
296   1896276     2            8.4         6           0  533.2  370360.953557
297   1758223     2            9.5         4           0  367.1  261046.591659
298   1752010     0            2.6         3           0  291.3  154248.646967
299   1651404     3            7.8         6           0  517.0  384854.666935

[300 rows x 7 columns]